[[redirects]]
  from = "/api/*"
  to = "http://95.163.221.125:8080/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", X-From = "Netlify", X-Forwarded-Host = "95.163.221.125:8080" }