[[redirects]]
  from = "/api/auth/users/login"
  to = "http://95.163.221.125:8080/auth/users/login"
  status = 200
  force = true

  [[headers]]
    for = "/*"
    [headers.values]
      Content-Type = "application/json"